# # frontend

# import streamlit as st
# import requests
# import datetime

# # BASE_URL = 'http://localhost:8000'  # Backend endpoint
# BASE_URL = 'https://ai-trip-planner-backend-jrdl.onrender.com'  # Backend endpoint

# st.set_page_config(
#     page_title="Roamio AI",
#     page_icon="🌏",
#     layout="centered",
#     initial_sidebar_state='expanded'
# )

# st.markdown("""
# <div style='text-align: center; padding: 15px 0;'>
#     <h1 style='
#         font-size: 2.8rem; 
#         margin: 0;
#         font-weight: 600;
#     '>🌏 <span style='
#         background: linear-gradient(45deg, #4facfe 0%, #00f2fe 100%);
#         -webkit-background-clip: text;
#         -webkit-text-fill-color: transparent;
#     '>Roamio AI</span></h1>
#     <p style='
#         color: #7c8db5;
#         margin: 5px 0;
#         font-size: 1rem;
#         font-style: italic;
#     '>Your AI Trip Planner by Omkar, built with complete guidance from Krish Naik & Sunny Sir.</p>
# </div>
# """, unsafe_allow_html=True)

# # Initialize chat history
# if 'messages' not in st.session_state:
#     st.session_state.messages = []

# # Display prompt
# st.header('🧭 Where shall we explore next?')

# with st.sidebar:
#    # Beautiful header
#    st.markdown("""
#    <div style='text-align: center; padding: 10px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 8px; margin-bottom: 15px;'>
#        <h4 style='color: white; margin: 0;'>Hey Buddy Welcome ✈️</h4>
#    </div>
#    """, unsafe_allow_html=True)
   
#    st.markdown("### 🎯 Quick Tips")
#    st.markdown("""
#                - For best results, prompt AI with as much details as possible
                
#                - Example: plan a 5 day trip to usa for 5 people, we prefer beaches, convert the currency from usd to inr, per person budget is between 10 lakh to 11 lakhs inr
#                """)
   
#    st.divider()
   
#    # Fun travel facts
#    st.markdown("### 🌍 Did You Know?")
   
#    facts = [
#        "🏔️ Nepal has 8 of the world's 10 tallest mountains",
#        "🌊 Maldives has 1,192 coral islands",
#        "🕌 India has 38 UNESCO World Heritage Sites"
#    ]
   
#    import random
#    daily_fact = random.choice(facts)
#    st.info(daily_fact)
   
#    st.divider()
      
#    # Footer
#    st.markdown("""
#    <div style='text-align: center; color: #888;'>
#        <small>🤖 Your AI Travel Buddy</small>
#    </div>
#    """, unsafe_allow_html=True)

# # Chat input box
# with st.form(key='query_form', clear_on_submit=True):
#     user_input = st.text_input('Prompt Here')
#     submit_button = st.form_submit_button('Ask AI')

# if submit_button and user_input.strip():
#     try:
#         with st.spinner('Roamio AI is thinking...'):
#             payload = {'query': user_input}
#             response = requests.post(f'{BASE_URL}/query', json=payload)

#         if response.status_code == 200:
#             answer = response.json().get('answer', 'No answer returned.')

#             # answer = answer.strip()

#             st.write(f'**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}')
#             st.write(f'**Created by:** Omkar\'s Roamio AI Trip Planner')

#             st.subheader('🧭 AI Trip Plan')

#             st.markdown(answer)

#             st.info('💡 *Note: This trip plan was generated by AI. Please verify all details like pricing, timings, and safety measures before your trip.*')

#             st.markdown("---")
#             st.markdown(
#                 """
#                 <div style='text-align: center; color: #666; padding: 10px;'>
#                     Made with ❤️ by Omkar, under the complete guidance of Krish Naik & Sunny Sir
#                 </div>
#                 """, 
#                 unsafe_allow_html=True
#             )
            
            
#         else:
#             st.error('❌ AI failed to respond: ' + response.text)

#     except Exception as e:
#         st.error(f'🚨 The response failed due to: {e}')


















































import streamlit as st
import requests
import datetime

BASE_URL = 'https://ai-trip-planner-backend-jrdl.onrender.com'

st.set_page_config(
    page_title="Roamio",
    page_icon="✈️",
    layout="centered",
    initial_sidebar_state='expanded'
)

# Luxury Header
st.markdown("""
<div style='text-align: center; padding: 25px 0; background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%); border-radius: 15px; margin-bottom: 30px; border: 1px solid #333;'>
    <h1 style='
        font-size: 3.2rem; 
        margin: 0;
        font-weight: 300;
        letter-spacing: 3px;
        color: #fff;
        font-family: "Times New Roman", serif;
    '>✈️ ROAMIO <span style='
        background: linear-gradient(45deg, #d4af37, #ffd700, #ffed4e);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-weight: 600;
    '>AI</span></h1>
    <p style='
        color: #b8860b;
        margin: 10px 0;
        font-size: 1.1rem;
        font-style: italic;
        letter-spacing: 1px;
    '>AI Trip Planner by Omkar · Guided by Krish Naik & Sunny Sir</p>
</div>
""", unsafe_allow_html=True)

# Elegant Input Section
st.markdown("""
<div style='background: linear-gradient(135deg, #2c2c54 0%, #40407a 100%); padding: 20px; border-radius: 12px; margin: 20px 0; border: 1px solid #555;'>
    <h3 style='color: #d4af37; text-align: center; margin-bottom: 15px; font-weight: 300; letter-spacing: 2px;'>🌍 DESTINATION INQUIRY</h3>
</div>
""", unsafe_allow_html=True)

with st.sidebar:
    st.markdown("""
    <div style='text-align: center; padding: 15px; background: linear-gradient(135deg, #2c2c54 0%, #40407a 100%); border-radius: 10px; margin-bottom: 20px; border: 1px solid #444;'>
        <h4 style='color: #d4af37; margin: 0; letter-spacing: 1px;'>CONCIERGE SERVICES ✨</h4>
    </div>
    """, unsafe_allow_html=True)
    
    st.markdown("### 🎯 Some Recommendations")
    st.markdown("""
    **For premium itineraries, include:**
    - Destination preferences & duration
    - Group size & luxury tier
    - Budget range in preferred currency
    - Special experiences desired
    """)
    
    st.divider()
    
    st.markdown("### 💎 Exclusive Insights")
    luxury_facts = [
    "🏰 Dubai has the world's only 7-star hotel",
    "🍾 Monaco has more millionaires per capita than anywhere",
    "🌸 Japan's cherry blossom season lasts only 2 weeks",
    "💎 The Ritz Paris has a $18,000 per night Imperial Suite",
    "🛥️ Superyachts over 100m cost $275 million+ to build",
    "🏔️ Switzerland's Zermatt bans all cars except electric vehicles",
    "🍸 The world's most expensive cocktail costs $12,970",
    "✈️ Private jets can cost $90 million for ultra-long range models",
    "🏖️ The Bahamas has 365 islands, one for each day",
    "🌊 The Maldives has overwater villas costing $50,000+ per night",
    "🎭 Venice receives 30 million tourists annually in just 5 square km",
    "🍷 A bottle of 1945 Romanée-Conti sold for $558,000",
    "🏨 Tokyo has more Michelin stars than Paris and London combined",
    "🚁 Helicopter tours in NYC cost $200+ per person for 15 minutes",
    "🌺 Bora Bora's overwater bungalows were invented in 1967",
    "🎪 Monaco's casino generates 4% of the country's revenue",
    "🏛️ The Vatican is the smallest country at 0.17 square miles",
    "🦅 Dubai's Burj Al Arab uses 22-carat gold leaf on interiors",
    "🌴 Seychelles has beaches with naturally pink sand",
    "❄️ Antarctica luxury cruises cost $15,000+ per person"
    ]
    
    import random
    st.info(random.choice(luxury_facts))

    st.markdown("### 🌐 Connect With Us")
    st.markdown("""
    <div style='text-align: center;'>
        <a href='https://github.com/your_username' target='_blank' style='text-decoration: none; margin: 0 10px;'>
            <span style='font-size: 15px;'>GitHub</span>
        </a>
        <a href='https://instagram.com/your_handle' target='_blank' style='text-decoration: none; margin: 0 10px;'>
            <span style='font-size: 15px;'>Instagram</span>
        </a>
    </div>
    """, unsafe_allow_html=True)

# Premium Input Form
with st.form(key='concierge_form', clear_on_submit=True):
    user_input = st.text_area('Share your travel aspirations...', height=100, placeholder="Describe your dream journey...")
    submit_button = st.form_submit_button('✨ Consult Roamio', use_container_width=True)

if submit_button and user_input.strip():
    try:
        with st.spinner('🔮 Crafting your bespoke itinerary...'):
            response = requests.post(f'{BASE_URL}/query', json={'query': user_input})

        if response.status_code == 200:
            answer = response.json().get('answer', 'No recommendations available.')

            # Elegant Results Display
            st.markdown("""
            <div style='background: linear-gradient(135deg, #1a1a2e 0%, #2c2c54 100%); padding: 20px; border-radius: 12px; margin: 20px 0; border: 1px solid #333;'>
                <h3 style='color: #d4af37; text-align: center; margin-bottom: 15px; letter-spacing: 2px;'>📋 CURATED ITINERARY</h3>
            </div>
            """, unsafe_allow_html=True)
            
            st.markdown(f'**Crafted:** {datetime.datetime.now().strftime("%Y-%m-%d at %H:%M")}')
            st.markdown(f'**By:** Roamio')
            
            st.markdown(answer)
            
            st.success('💼 **Roamio\'s Note:** Please verify all arrangements with official sources before travel.')
            
            st.markdown("---")
            st.markdown("""
            <div style='text-align: center; background: linear-gradient(135deg, #1a1a2e 0%, #2c2c54 100%); padding: 15px; border-radius: 8px; border: 1px solid #333;'>
                <span style='color: #d4af37; font-style: italic;'>Crafted with Excellence | Roamio Concierge</span>
            </div>
            """, unsafe_allow_html=True)
            
        else:
            st.error('⚠️ Concierge service temporarily unavailable')

    except Exception as e:
        st.error(f'🚨 Service interruption: {e}')